import {StyleSheet} from 'react-native';
import {
  responsiveHeight,
  responsiveWidth,
  responsiveFontSize,
} from 'react-native-responsive-dimensions';
import Colors from '../../../services/constants/colors';
import Fonts from '../../../services/constants/fonts';
// define your styles
const styles = StyleSheet.create({
  container: {
    flex: 1,
    // flexGrow: 0,
    backgroundColor: Colors.white,
  },
  scView: {
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 30,
    flexDirection: 'row',
    marginBottom: 10,
  },
  selfTxt: {
    fontFamily: Fonts.poppinsExtraBold,
    fontSize: responsiveFontSize(5),
    color: Colors.purple,
  },
  checkTxt: {
    textAlign: 'center',
    fontFamily: Fonts.poppinsExtraBold,
    fontSize: responsiveFontSize(5),
    color: Colors.white,
    backgroundColor: Colors.purple,
    marginHorizontal: 10,
    alignItems: 'center',
    borderWidth: 1,
    borderRadius: 70,
    padding: 1,
  },

  txt1: {
    alignItems: 'center',
    marginTop: 30,
    fontFamily: Fonts.poppinsRegular,
    fontSize: responsiveFontSize(2),
    color: Colors.black,
  },
  parent: {
    top: 50,
    height: responsiveHeight(100),
    width: responsiveWidth(100),
    borderTopStartRadius: 500,
    borderTopEndRadius: 500,
    backgroundColor: Colors.lightGrey,
    transform: [{scaleX: 1.5}],
    overflow: 'hidden',
  },
  child: {
    marginTop: 15,
    height: responsiveHeight(100),
    width: responsiveWidth(100),
    borderTopStartRadius: 400,
    borderTopEndRadius: 400,
    backgroundColor: Colors.purple,
    alignItems: 'center',
    transform: [{scaleX: 1}],
    overflow: 'hidden',
  },
  viewS2: {
    transform: [{scaleX: 0.7}],
    alignItems: 'center',
    marginTop: 150,
    justifyContent: 'center',
  },
  subTxt: {
    paddingVertical: 1,
    paddingTop: 10,
    textAlign: 'center',
    color: Colors.purple,
    padding: 20,
    fontFamily: Fonts.poppinsThin,
    fontSize: responsiveFontSize(1.7),
    marginTop: 12,
  },
  btnView: {
    marginTop: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  btnTxtStyle: {
    fontFamily: Fonts.poppinsBold,
    justifyContent: 'center',
    alignItems: 'center',
    color: Colors.white,
  },
  btnToStyle: {
    justifyContent: 'center',
    backgroundColor: Colors.orange,
    width: responsiveWidth(80),
    height: responsiveHeight(5),
    alignItems: 'center',
    borderRadius: 12,
    marginTop: 10,
  },
  btnView1: {
    marginTop: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  btnTxtStyle1: {
    fontFamily: Fonts.poppinsBold,
    justifyContent: 'center',
    alignItems: 'center',
    color: Colors.white,
  },
  btnToStyle1: {
    justifyContent: 'center',
    backgroundColor: Colors.purple,
    width: responsiveWidth(80),
    height: responsiveHeight(5),
    alignItems: 'center',
    borderRadius: 12,
    marginTop: 10,
    borderColor:Colors.lightGrey,
    opacity:0.5,
    borderWidth: 1,
  },
  viewCombo: {
    flexDirection: 'row',
  },
  btnView2: {
    marginTop: 10,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 18,
  },
  btnTxtStyle2: {
    fontFamily: Fonts.poppinsBold,
    justifyContent: 'center',
    alignItems: 'center',
    color: Colors.white,
  },
  btnToStyle2: {
    justifyContent: 'center',
    backgroundColor: Colors.purple,
    width: responsiveWidth(38),
    height: responsiveHeight(5),
    alignItems: 'center',
    borderRadius: 12,
    marginTop: 10,
  },
  btnView3: {
    marginTop: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  btnTxtStyle3: {
    fontFamily: Fonts.poppinsBold,
    justifyContent: 'center',
    alignItems: 'center',
    color: Colors.white,
  },
  btnToStyle3: {
    justifyContent: 'center',
    backgroundColor: Colors.orange,
    width: responsiveWidth(38),
    height: responsiveHeight(5),
    alignItems: 'center',
    borderRadius: 12,
    marginTop: 10,
  },
  westIcon: {
    left: -60,
    fontSize: responsiveFontSize(4),
    color: Colors.purple,
  },
});
export default styles;
