import {StyleSheet} from 'react-native';
import {
  responsiveHeight,
  responsiveWidth,
  responsiveFontSize,
} from 'react-native-responsive-dimensions';
// define your styles
const styles = StyleSheet.create({
  container: {
    flex: 1,
    //justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'white',
  },
  scView: {
    marginLeft: 40,
    marginTop: 30,
    flexDirection: 'row',
    marginBottom: 10,
  },
  selfTxt: {
    fontFamily: 'Poppins-Bold',
    fontSize: responsiveFontSize(5),
    fontWeight: 'bold',
    color: 'rgba(51, 41, 93, 1)',
  },
  checkTxt: {
  //   justifyContent:'center',
  //  textAlign: 'center',
    fontFamily: 'Poppins-Bold',
    height: responsiveHeight(6),
    width: responsiveWidth(30),
    fontSize: responsiveFontSize(5),
    fontWeight: 'bold',
    color: 'white',
    backgroundColor: 'rgba(51, 41, 93, 1)',
    marginHorizontal: 10,
    // alignItems: 'center',
    borderWidth: 0.2,
    borderRadius: 30,
    padding: 1,
  },

  viewS1: {
    flexDirection: 'row',
    marginTop: 60,
    alignItems: 'center',
  },
  viewImg1: {
    paddingVertical: 0,
    //justifyContent:'center',
    marginHorizontal: 30,
    alignItems: 'center',
  },
  img1: {
    paddingVertical: 0,
    height: responsiveHeight(5),
    width: responsiveWidth(12),
  },
  txtImg1: {
    paddingVertical: 0,
    padding: 2,
    paddingTop: 6,
    textAlign: 'center',
    fontWeight: '700',
    fontFamily: 'Poppins-Regular',
    color: 'black',
  },
  viewImg2: {
    paddingVertical: 0,
    justifyContent: 'center',
    marginHorizontal: 30,
    alignItems: 'center',
  },
  img2: {
    paddingVertical: 0,
    height: responsiveHeight(5),
    width: responsiveWidth(13),
  },
  txtImg2: {
    paddingVertical: 0,
    padding: 2,
    paddingTop: 9,
    textAlign: 'center',
    fontWeight: '700',
    fontFamily: 'Poppins-Regular',
    color: 'black',
  },
  viewImg3: {
    paddingVertical: 0,
    //justifyContent:'center',
    marginHorizontal: 30,
    alignItems: 'center',
  },
  img3: {
    paddingVertical: 0,
    height: responsiveHeight(6.5),
    width: responsiveWidth(12),
  },
  txtImg3: {
    paddingVertical: 0,
    padding: 2,
    paddingTop: 6,
    textAlign: 'center',
    fontWeight: '700',
    fontFamily: 'Poppins-Regular',
    color: 'black',
  },
  parent: {
    marginTop: 50,
    height: responsiveHeight(35),
    width: responsiveWidth(100),
    //borderRadius:200,
    borderTopStartRadius: 400,
    borderTopEndRadius: 400,
    borderBottomStartRadius: 400,
    borderBottomEndRadius: 400,
    backgroundColor: '#d6d4df',
    transform: [{scaleX: 1.5}],
    overflow: 'hidden',
  },
  child: {
    marginTop: 12,
    height: responsiveHeight(32),
    width: responsiveWidth(100),
    borderTopStartRadius: 400,
    borderTopEndRadius: 400,
    borderBottomStartRadius: 400,
    borderBottomEndRadius: 400,
    backgroundColor: '#33295d',
    // justifyContent:'center',
    alignItems: 'center',
    transform: [{scaleX: 1}],
  },
  viewS2: {
    transform: [{scaleX: 0.56}],
    alignItems: 'center',
    marginTop: 80,
    justifyContent: 'center',
  },
  viewSos: {
    paddingVertical: 0,
    alignItems: 'center',
    justifyContent: 'center',
    //flexDirection:'row',
    backgroundColor: 'red',
    width: responsiveWidth(40),
    height: responsiveHeight(15),
    borderRadius: 20,
  },
  iconSos: {
    color: 'red',
    fontSize: responsiveFontSize(4),
    fontWeight: 'bold',
    borderRadius: 20,
    backgroundColor: '#fff',
    padding: 5,
  },
  txtSos: {
    textAlign: 'center',
    color: '#fff',
    fontSize: responsiveFontSize(8),
    fontWeight: 'bold',
    padding: 2,
  },
  viewS3: {
    flexDirection: 'row',
    marginTop: 60,
    alignItems: 'center',
  },
  viewImg4: {
    paddingVertical: 0,
    //justifyContent:'center',
    marginHorizontal: 60,
    alignItems: 'center',
  },
  img4: {
    paddingVertical: 0,
    height: responsiveHeight(6.5),
    width: responsiveWidth(14),
  },
  txtImg4: {
    paddingVertical: 0,
    padding: 2,
    paddingTop: 6,
    textAlign: 'center',
    fontWeight: '700',
    fontFamily: 'Poppins-Regular',
    color: 'black',
  },
  viewImg5: {
    paddingVertical: 0,
    //justifyContent:'center',
    marginHorizontal: 50,
    alignItems: 'center',
  },
  img5: {
    paddingVertical: 0,
    height: responsiveHeight(6.5),
    width: responsiveWidth(16),
  },
  txtImg5: {
    paddingVertical: 0,
    padding: 2,
    paddingTop: 6,
    textAlign: 'center',
    fontWeight: '700',
    fontFamily: 'Poppins-Regular',
    color: 'black',
  },
  iconContact: {
    padding: 10,
    paddingLeft:40,
    color: '#33295d',
    fontSize: responsiveFontSize(4),
  },
  iconLogout:{
    padding: 20,
    left: -60,
    color: 'black',
    fontSize: responsiveFontSize(3),
  }
});
export default styles;
