import {StyleSheet} from 'react-native';
import {
  responsiveHeight,
  responsiveWidth,
  responsiveFontSize,
} from 'react-native-responsive-dimensions';
import Colors from '../../../services/constants/colors';
// define your styles
const styles = StyleSheet.create({
  container: {
    flex: 1,
    //justifyContent: 'center',
    // alignItems: 'center',
    backgroundColor: Colors.white,
  },
  scView: {
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 30,
    flexDirection: 'row',
    marginBottom: 10,
  },
  selfTxt: {
    fontFamily: 'Poppins-Bold',
    fontSize: responsiveFontSize(5),
    fontWeight: 'bold',
    color: Colors.purple,
  },
  checkTxt: {
    textAlign: 'center',
    fontFamily: 'Poppins-Bold',
    fontSize: responsiveFontSize(5),
    fontWeight: 'bold',
    color: Colors.white,
    backgroundColor: Colors.purple,
    marginHorizontal: 10,
    alignItems: 'center',
    borderWidth: 1,
    borderRadius: 70,
    padding: 1,
  },

  txt1: {
    alignItems: 'center',
    marginTop: 30,
    fontFamily: 'Poppins-Regular',
    fontSize: responsiveFontSize(2.5),
    fontWeight: '700',
    color: Colors.white,
  },
  parent: {
    top: 50,
    height: responsiveHeight(100),
    width: responsiveWidth(100),
    borderTopStartRadius: 500,
    borderTopEndRadius: 500,
    backgroundColor: Colors.lightGrey,
    //borderBottomStartRadius : 200,
    //borderBottomEndRadius : 200,
    //overflow : 'hidden',
    transform: [{scaleX: 1.5}],
    overflow: 'hidden',
  },
  child: {
    marginTop: 15,
    height: responsiveHeight(100),
    width: responsiveWidth(100),
    borderTopStartRadius: 400,
    borderTopEndRadius: 400,
    backgroundColor: Colors.purple,
    // justifyContent:'center',
    alignItems: 'center',
    transform: [{scaleX: 1}],
    overflow: 'hidden',
  },
  viewS2: {
    transform: [{scaleX: 0.56}],
    alignItems: 'center',
    marginTop: 50,
    justifyContent: 'center',
  },
  iconView: {
    marginTop: 15,
    width: responsiveWidth(16),
    height: responsiveHeight(8),
    borderRadius: 500,
    backgroundColor: Colors.white,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 20,
  },
  icon: {
    textAlign: 'center',
    fontSize: responsiveFontSize(5.5),
    color: Colors.purple,
  },
  mainTxt: {
    textAlign: 'center',
    //alignItems:'center',
    marginTop: 10,
    fontFamily: 'Poppins-Regular',
    fontSize: responsiveFontSize(3.5),
    fontWeight: '700',
    color: Colors.white,
  },
  subTxt: {
    paddingLeft: 20,
    alignItems: 'center',
    fontFamily: 'Poppins-Regular',
    fontSize: responsiveFontSize(1.7),
    fontWeight: '700',
    color: Colors.white,
  },
  icon1View: {
    marginHorizontal: 4,
    width: responsiveWidth(5),
    height: responsiveHeight(2),
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 450,
    backgroundColor: Colors.white,
  },
  icon1: {
    right: -9,
    color: Colors.white,
    textAlign: 'center',
    fontSize: responsiveFontSize(5.5),
  },
  icon2: {
    right: 15,
    paddingTop: 8,
    color: Colors.white,
    textAlign: 'center',
    fontSize: responsiveFontSize(3),
  },
  toNext: {
    justifyContent: 'center',
    backgroundColor: Colors.orange,
    width: responsiveWidth(80),
    height: responsiveHeight(5),
    alignItems: 'center',
    borderRadius: 12,
    marginTop: 10,
  },
  datePickerStyle: {
    flexDirection: 'row',
    width: responsiveWidth(80),
    height: responsiveHeight(5),
    alignItems: 'center',
    borderRadius: 12,
    backgroundColor: Colors.purple,
    borderColor: Colors.lightGrey,
    borderWidth: 2,
    padding: 1.7,
    opacity: 0.5,
  },
  pickerView: {
    width: responsiveWidth(80),
    height: responsiveHeight(5),
    //alignItems: 'center',
    borderRadius: 12,
    backgroundColor: Colors.purple,
    borderColor: Colors.lightGrey,
    borderWidth: 2,
    //padding: 1.7,
    opacity: 0.5,
    justifyContent: 'center',
    marginBottom: 20,
  },
  picker: {
    alignItems: 'center',
    justifyContent: 'center',
    color: Colors.white,
    marginTop: 4,
    //padding: 1.7,
    fontSize: responsiveFontSize(1),
  },
  pickerItem: {
    fontSize: responsiveFontSize(1.7),
  },
  textiS: {
    marginLeft: 10,
    flexWrap: 'wrap',
    marginRight: 200,
    paddingVertical: 0,
  },
  btnView: {
    marginTop: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  saveBtnS: {
    fontFamily: 'Poppins',
    justifyContent: 'center',
    alignItems: 'center',
    color: Colors.white,
    fontWeight: '700',
  },
  saveToS: {
    justifyContent: 'center',
    backgroundColor: Colors.orange,
    width: responsiveWidth(80),
    height: responsiveHeight(5),
    alignItems: 'center',
    borderRadius: 12,
    marginTop: 10,
  },
});
export default styles;
