import { StyleSheet } from 'react-native';
import {
    responsiveHeight,
    responsiveWidth,
    responsiveFontSize
  } from "react-native-responsive-dimensions";
// define your styles
const styles = StyleSheet.create({
    container: {
        flex: 1,
        //justifyContent: 'center',
       // alignItems: 'center',
        backgroundColor: 'white',
    },
    scView:{
        justifyContent: 'center',
        alignItems:'center',
        marginTop:30,
        flexDirection:'row',
        marginBottom:10,
    },
    selfTxt:{
        fontFamily:'Poppins-Bold',
        fontSize:responsiveFontSize(5),
        fontWeight:'bold',
        color:'rgba(51, 41, 93, 1)',
    },
    checkTxt:{
        textAlign:'center',
        fontFamily:'Poppins-Bold',
        fontSize:responsiveFontSize(5),
        fontWeight:'bold',
        color:'white',
        backgroundColor:'rgba(51, 41, 93, 1)',
        marginHorizontal: 10,
        alignItems:'center',
        borderWidth: 1,
        borderRadius:70,
        padding:1
    },
   
    txt1:{
        alignItems:'center',
        marginTop:30,
        fontFamily:'Poppins-Regular',
        fontSize:responsiveFontSize(2.5),
        fontWeight:'700',
        color:'white',
    },
    parent: {
        //To make Circle Shape
        marginTop: 30,
        width:  responsiveWidth(100),
        height: responsiveHeight(73),
        //borderRadius:800,
        borderTopStartRadius : 300,
        borderTopEndRadius :300,
        borderBottomStartRadius :300,
        borderBottomEndRadius : 300,
        overflow : 'hidden',
        backgroundColor: '#d6d4df',
        transform : [ { scaleX : 1.5 } ],
        
    },
    child: {
        //To make Circle Shape
        marginTop: 13,
        width:  responsiveWidth(100),
        height: responsiveHeight(70),
        borderTopStartRadius : 300,
        borderTopEndRadius : 300,
        borderBottomStartRadius : 300,
        borderBottomEndRadius : 300,
        backgroundColor: '#33295d',
        transform : [ { scaleX : 1 } ],
        overflow:"hidden"
    },
    viewS2:{
        transform :[{scaleX:0.7}],
        alignItems:"center", 
        marginTop:50, 
        justifyContent:'center',
    },
    iconView:{
        marginTop:15, 
        width:  responsiveWidth(21),
        height: responsiveHeight(9),
        borderRadius:500,
        backgroundColor: 'white',
        alignItems:"center",  
        justifyContent:"center",
        marginBottom:20,
    },
    icon:{
        
        textAlign:'center',
        fontSize: responsiveFontSize(5.5),
        color:"#33295d",
    },
    mainTxt:{
        textAlign:'center',
        //alignItems:'center',
        marginTop:10,
        fontFamily:'Poppins-Regular',
        fontSize:responsiveFontSize(3.5),
        fontWeight:'700',
        color:'white',
    },
    subTxt:{
        paddingLeft:20,
        alignItems:'center',
        fontFamily:'Poppins-Regular',
        fontSize:responsiveFontSize(1.7),
        fontWeight:'700',
        color:'white',
    },
    icon1View:{
       // marginHorizontal:4,
        width:  responsiveWidth(20),
        height: responsiveHeight(2),
        alignItems:"center",  
        justifyContent:"center",
        borderRadius:450,
        backgroundColor: 'white',
    },
    icon1:{ 
        right:-15,
        color:'white',
        //textAlign:'center',
        fontSize: responsiveFontSize(5.5),
    },
    icon2:{ 
        right:-40,
        paddingTop:8,
        color:'white',
        textAlign:'center',
        fontSize: responsiveFontSize(3),
    },
    txtinpView:{
      
        width:responsiveWidth(80),
        height: responsiveHeight(5),
        borderRadius: 12,
        marginTop:20, 
        justifyContent:"center",
        backgroundColor: 'rgba(214, 212, 223, 1)',
        opacity:0.5,

    },
   
    textiS:{
        flexWrap:'wrap',
        fontSize: responsiveFontSize(1.5),
        left:10,
       // marginLeft:10,
        flexWrap:'wrap',
      //  marginRight:200,
        paddingVertical: 0,
    },
    textiS1:{
        
        flexWrap:'wrap',
        fontSize: responsiveFontSize(1.5),
        left:-2,
       // marginLeft:10,
        flexWrap:'wrap',
      //  marginRight:200,
        paddingVertical: 0,
    },
    textiS2:{
        
        flexWrap:'wrap',
        fontSize: responsiveFontSize(1.5),
        left:-45,
       // marginLeft:10,
        flexWrap:'wrap',
      //  marginRight:200,
        paddingVertical: 0,
    },
    btnView:{
        marginTop:10,
        justifyContent:"center",
        alignItems:"center",
    },
    saveBtnS:{
        fontFamily:"Poppins", 
        justifyContent:"center",
        alignItems:"center",
        color:"#f7f7f7",
        fontWeight: "700",
    },
    saveToS:{
        justifyContent:"center",
        backgroundColor: "#ff8945",
        width:responsiveWidth(80),
        height: responsiveHeight(5),
        alignItems:'center' ,
        borderRadius: 12,
        marginTop:10,
    },
    txtStyle:{
        color:'white',
        marginTop:25,
        textAlign:'center',
        marginBottom:10,
    },
    toSub: {
        justifyContent: "center",
        backgroundColor: "#ff8945",
        width: responsiveWidth(80),
        height: responsiveHeight(5),
        alignItems: 'center',
        borderRadius: 12,
        marginTop: 10,
    },
    pickerView: {
        width: responsiveWidth(80),
        height: responsiveHeight(5),
        //alignItems: 'center',
        borderRadius: 12,
        backgroundColor: '#33295d',
        borderColor: '#D6D4DF',
        borderWidth: 2,
        //padding: 1.7,
        opacity: 0.5,
        justifyContent: 'center',
        marginBottom: 20,
      },
      picker: {
        alignItems: 'center',
        justifyContent: 'center',
        color: 'white',
        marginTop: 4,
        //padding: 1.7,
        fontSize: responsiveFontSize(1),
      },
      pickerItem: {
        fontSize: responsiveFontSize(0.5),
      },
});
export default styles