import {StyleSheet} from 'react-native';
import {
  responsiveHeight,
  responsiveWidth,
  responsiveFontSize,
} from 'react-native-responsive-dimensions';
import Fonts from '../../../services/constants/fonts';
import Colors from '../../../services/constants/colors';
// define your styles
const styles = StyleSheet.create({
  container: {
    flex: 1,
    bottom:1,
    // flexGrow: 0,
    alignItems: 'center',
    backgroundColor: Colors.white,
  },
  viewS1: {
    marginTop: 30,
    flexDirection: 'row',
    marginBottom: 10,
  },
  txtS1: {
    fontFamily: Fonts.poppinsBold,
    fontSize: responsiveFontSize(5),
    color: Colors.purple,
  },
  txtS2: {
    textAlign: 'center',
    fontFamily: Fonts.poppinsExtraBold,
    fontSize: responsiveFontSize(5),
    color: Colors.white,
    backgroundColor: Colors.purple,
    marginHorizontal: 10,
    alignItems: 'center',
    borderWidth: 1,
    borderRadius: 70,
    padding: 1,
  },
  parentView: {
    marginTop: 30,
    width: responsiveWidth(100),
    height: responsiveHeight(73),
    borderTopStartRadius: 300,
    borderTopEndRadius: 300,
    borderBottomStartRadius: 300,
    borderBottomEndRadius: 300,
    overflow: 'hidden',
    backgroundColor: Colors.lightGrey,
    transform: [{scaleX: 2}],
  },
  childView: {
    marginTop: 13,
    width: responsiveWidth(100),
    height: responsiveHeight(70),
    borderTopStartRadius: 300,
    borderTopEndRadius: 300,
    borderBottomStartRadius: 300,
    borderBottomEndRadius: 300,
    backgroundColor: Colors.purple,
    transform: [{scaleX: 1}],
    overflow: 'hidden',
  },
  viewS2: {
    transform: [{scaleX: 0.5}],
    alignItems: 'center',
    marginTop: 10,
    justifyContent: 'center',
  },
  backArrowView: {
    marginTop: 15,
    width: responsiveWidth(16),
    height: responsiveHeight(8),
    borderRadius: 450,
    backgroundColor: Colors.white,
    alignItems: 'center',
    justifyContent: 'center',
  },
  backArrow: {
    fontSize: responsiveFontSize(4),
    color: Colors.black,
  },
  wbS: {
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 20,
    color: Colors.white,
    fontFamily: Fonts.poppinsBold,
    fontSize: responsiveFontSize(4),
    marginBottom: 10,
  },
  wbS1: {
    textAlign: 'center',
    justifyContent: 'center',
    alignItems: 'center',
    fontFamily: Fonts.poppinsBold,
    fontSize: responsiveFontSize(2),
    color: Colors.white,
  },

  fpassView: {
    marginTop: -6,
    alignItems: 'center',
  },
  fpassToStle: {
    alignItems: 'flex-start',
    left: -100,
  },
  txtFpass: {
    color: Colors.lightGrey,
  },
  viewS7: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 10,
    justifyContent: 'center',
  },
  toStyle2: {
    paddingLeft: 6,
  },
  txtS3: {
    color: Colors.purple,
    fontFamily: Fonts.poppinsBold,
  },
  txtS4: {
    flex: 1,
    paddingVertical: 0,
    color: Colors.orange,
    fontFamily: Fonts.poppinsBold,
  },
  btnSigninView: {
    marginTop: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  signinS: {
    fontFamily: Fonts.poppinsExtraBold,
    justifyContent: 'center',
    alignItems: 'center',
    color: Colors.white,
  },
  toSignin: {
    justifyContent: 'center',
    backgroundColor: Colors.orange,
    width: responsiveWidth(80),
    height: responsiveHeight(5),
    alignItems: 'center',
    borderRadius: 12,
    marginTop: 10,
  },
  fpViewS: {
    alignItems: 'center',
    marginTop: 20,
    justifyContent: 'center',
  },
  fpStyle: {
    opacity: 0.5,
    fontSize: responsiveFontSize(6),
    color: Colors.white,
  },
  flStyle: {
    fontFamily: Fonts.poppinsBold,
    color: Colors.white,
    marginTop: 10,
  },
  googleButtonStyle: {
    marginTop: 6,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  googleTxt: {
    paddingLeft: 10,
    color: Colors.white,
  },
  googleAndPhoneStyle: {
    marginTop: 6,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  verticalLine: {
    marginTop: 10,
    marginLeft: 20,
    marginRight: 20,
    alignItems: 'center',
    justifyContent: 'center',
    width: responsiveHeight(0.1),
    height: responsiveHeight(0.1),
    backgroundColor: Colors.lightGrey,
    paddingTop: 10,
    paddingBottom: 10,
  },
  horizontalLine: {
    top: 20,
    margin: 10,
    borderBottomColor: Colors.black,
    borderBottomWidth: 2,
    borderColor: Colors.lightGrey,
  },
  googleImg: {
    height: responsiveHeight(2),
    width: responsiveWidth(4),
  },
  signinTxt: {
    textAlign: 'center',
    color: Colors.white,
    marginTop: 20,
    marginBottom: 2,
  },
  phoneImg: {
    height: responsiveHeight(2),
    width: responsiveWidth(4),
  },
});
export default styles;
